#  /**
#    * Dikkat!
#    * SMSS ile kullanıcı oluşturulmalı ilgili veritabana setlenmeli ve yetkileri verilmelidir.
#    * Diğer dikkat edilmesi gereken hususlar: connect sql grant olarak ayarlanmalıdır,
#    * configuration'dan ip all portu 1433 olarak verilmelidir.
#    */

url: jdbc:sqlserver://localhost:1433;databaseName=ibb_java_se;trustServerCertificate=true;
username: user=mehmet;
password: password=123456
driver: com.microsoft.sqlserver.jdbc.SQLServerDriver