module org.example.ibb_ecodation_javafx {
    requires javafx.graphics;
    requires javafx.controls;
    requires javafx.fxml;
    requires javafx.web;
    requires org.controlsfx.controls;
    requires com.dlsc.formsfx;
    requires net.synedra.validatorfx;
    requires org.kordamp.ikonli.javafx;
    requires org.kordamp.bootstrapfx.core;
    requires com.h2database;
    requires sendgrid.java;
    requires jbcrypt;
    requires jakarta.xml.bind;
    requires io.reactivex.rxjava3;
    requires spring.context;
    requires spring.beans;
    requires org.apache.logging.log4j;
    requires org.apache.poi.ooxml;
    requires org.apache.pdfbox;
    requires richtextfx;
    requires com.microsoft.sqlserver.jdbc;
    requires com.fasterxml.jackson.databind;
    requires de.jensd.fx.glyphs.fontawesome;
    requires java.net.http;
    requires org.apache.logging.log4j.core;
    requires layout;
    requires io;
    requires kernel;
    requires org.apache.commons.io;
    requires static lombok;
    requires org.mapstruct;
    requires com.fasterxml.jackson.dataformat.yaml;
    requires java.desktop;
    requires java.sql;
    requires spring.core;
    requires spring.jdbc;
    requires java.annotation;
    requires spring.tx;
    requires org.slf4j;

    // Opens directives for reflective access
    opens org.example.ibb_ecodation_javafx to javafx.fxml, javafx.base, lombok, org.mapstruct, spring.beans, spring.core;
    opens org.example.ibb_ecodation_javafx.controller to javafx.fxml, lombok, org.mapstruct, spring.beans, spring.core;
    opens org.example.ibb_ecodation_javafx.ui.button to javafx.fxml, lombok, org.mapstruct;
    opens org.example.ibb_ecodation_javafx.ui.navbar to javafx.fxml, lombok, org.mapstruct;
    opens org.example.ibb_ecodation_javafx.ui.avatar to javafx.fxml, lombok, org.mapstruct;
    opens org.example.ibb_ecodation_javafx.ui.listItem to javafx.fxml, lombok, org.mapstruct;
    opens org.example.ibb_ecodation_javafx.ui.combobox to javafx.fxml, lombok, org.mapstruct;
    opens org.example.ibb_ecodation_javafx.ui.spinner to javafx.fxml, lombok, org.mapstruct;
    opens org.example.ibb_ecodation_javafx.ui.input to javafx.fxml, lombok, org.mapstruct;
    opens org.example.ibb_ecodation_javafx.service to javafx.fxml, lombok, org.mapstruct, spring.beans, com.fasterxml.jackson.databind;
    opens org.example.ibb_ecodation_javafx.ui.dragndrop to javafx.fxml, lombok, org.mapstruct, spring.beans;
    opens org.example.ibb_ecodation_javafx.ui.splitpane to javafx.fxml, lombok, org.mapstruct, spring.beans;
    opens org.example.ibb_ecodation_javafx.ui.chart to javafx.fxml, lombok, org.mapstruct, spring.beans;
    opens org.example.ibb_ecodation_javafx.ui.table to javafx.fxml, javafx.base, lombok, org.mapstruct, spring.beans;
    opens org.example.ibb_ecodation_javafx.ui.codehighlighter to javafx.fxml, javafx.base, lombok, org.mapstruct, spring.beans;
    opens org.example.ibb_ecodation_javafx.mapper to spring.beans;
    opens org.example.ibb_ecodation_javafx.repository to javafx.fxml, javafx.base, lombok, org.mapstruct, spring.beans, spring.core;
    opens org.example.ibb_ecodation_javafx.core.i18n to javafx.fxml, javafx.base, lombok, org.mapstruct, spring.beans;
    opens org.example.ibb_ecodation_javafx.core.service to javafx.fxml, javafx.base, lombok, org.mapstruct, spring.beans;
    opens org.example.ibb_ecodation_javafx.backup to javafx.fxml, lombok, org.mapstruct, spring.beans;
    opens org.example.ibb_ecodation_javafx.core.backup to javafx.fxml, lombok, org.mapstruct, spring.beans;
    opens org.example.ibb_ecodation_javafx.model to com.fasterxml.jackson.databind;
    opens org.example.ibb_ecodation_javafx.model.dto to com.fasterxml.jackson.databind;
    opens org.example.ibb_ecodation_javafx.model.request to com.fasterxml.jackson.databind;
    opens org.example.ibb_ecodation_javafx.model.response to com.fasterxml.jackson.databind;
    opens org.example.ibb_ecodation_javafx.model.enums to com.fasterxml.jackson.databind;
    opens org.example.ibb_ecodation_javafx.utils to javafx.fxml, javafx.base, lombok, org.mapstruct, spring.beans;
    opens org.example.ibb_ecodation_javafx.core.db to javafx.fxml, javafx.base, lombok, org.mapstruct, spring.beans;
    opens org.example.ibb_ecodation_javafx.config to javafx.fxml, javafx.base, lombok, org.mapstruct, spring.beans, spring.core;
    opens org.example.ibb_ecodation_javafx.core.config to javafx.fxml, javafx.base, lombok, org.mapstruct, spring.beans, spring.core, spring.context;
    opens org.example.ibb_ecodation_javafx.core.repository.impl to javafx.fxml, javafx.base, lombok, org.mapstruct, spring.beans, spring.core;
    opens org.example.ibb_ecodation_javafx.model.event to org.mapstruct, spring.beans;
    opens org.example.ibb_ecodation_javafx.core.mapper to spring.beans;
    opens org.example.ibb_ecodation_javafx.core.validation to spring.beans;
    opens org.example.ibb_ecodation_javafx.ui.datepicker  to javafx.fxml, javafx.base, lombok, org.mapstruct, spring.beans, spring.core, spring.context;


    // Exports directives for direct access
    exports org.example.ibb_ecodation_javafx to javafx.fxml, javafx.base, lombok, org.mapstruct, spring.beans, spring.core, javafx.graphics;
    exports org.example.ibb_ecodation_javafx.properties;
    exports org.example.ibb_ecodation_javafx.mapper;
    exports org.example.ibb_ecodation_javafx.model;
    exports org.example.ibb_ecodation_javafx.core.service;
    exports org.example.ibb_ecodation_javafx.core.service.impl;
    exports org.example.ibb_ecodation_javafx.utils;
    exports org.example.ibb_ecodation_javafx.core.i18n;
    exports org.example.ibb_ecodation_javafx.model.enums;
    exports org.example.ibb_ecodation_javafx.model.dto;
    exports org.example.ibb_ecodation_javafx.model.event;
    exports org.example.ibb_ecodation_javafx.repository;
    exports org.example.ibb_ecodation_javafx.core.db;
    exports org.example.ibb_ecodation_javafx.core.config;
    exports org.example.ibb_ecodation_javafx.core.mapper;
    exports org.example.ibb_ecodation_javafx.config;
    exports org.example.ibb_ecodation_javafx.core.repository.impl to spring.beans, spring.core;
    exports org.example.ibb_ecodation_javafx.repository.impl to spring.beans, spring.core; // Added for VatRepositoryImpl
}

//module org.example.ibb_ecodation_javafx {
//    requires javafx.graphics;
//    requires javafx.controls;
//    requires javafx.fxml;
//    requires javafx.web;
//    requires org.controlsfx.controls;
//    requires com.dlsc.formsfx;
//    requires net.synedra.validatorfx;
//    requires org.kordamp.ikonli.javafx;
//    requires org.kordamp.bootstrapfx.core;
//    requires com.h2database;
//    requires sendgrid.java;
//    requires jbcrypt;
//    requires jakarta.xml.bind;
//    requires io.reactivex.rxjava3;
//    requires spring.context;
//    requires spring.beans;
//    requires org.apache.logging.log4j;
//    requires org.apache.poi.ooxml;
//    requires org.apache.pdfbox;
//    requires richtextfx;
//    requires com.microsoft.sqlserver.jdbc;
//    requires com.fasterxml.jackson.databind;
//
//    opens org.example.ibb_ecodation_javafx  to javafx.fxml, javafx.base, lombok, org.mapstruct, spring.beans, spring.core;
//    opens org.example.ibb_ecodation_javafx.controller to javafx.fxml, lombok, org.mapstruct, spring.beans, spring.core;
//    opens org.example.ibb_ecodation_javafx.ui.button to javafx.fxml, lombok, org.mapstruct, spring.beans, com.fasterxml.jackson.databind;
//    opens org.example.ibb_ecodation_javafx.ui.navbar to javafx.fxml, lombok, org.mapstruct, spring.beans, com.fasterxml.jackson.databind;
//    opens org.example.ibb_ecodation_javafx.ui.avatar to javafx.fxml, lombok, org.mapstruct, spring.beans, com.fasterxml.jackson.databind;
//    opens org.example.ibb_ecodation_javafx.ui.listItem to javafx.fxml, lombok, org.mapstruct, spring.beans, com.fasterxml.jackson.databind;
//    opens org.example.ibb_ecodation_javafx.ui.combobox to javafx.fxml, lombok, org.mapstruct, spring.beans, com.fasterxml.jackson.databind;
//    opens org.example.ibb_ecodation_javafx.ui.spinner to javafx.fxml, lombok, org.mapstruct, spring.beans, com.fasterxml.jackson.databind;
//    opens org.example.ibb_ecodation_javafx.ui.input to javafx.fxml, lombok, org.mapstruct, spring.beans, com.fasterxml.jackson.databind;
//    opens org.example.ibb_ecodation_javafx.service to javafx.fxml, lombok, org.mapstruct, spring.beans, com.fasterxml.jackson.databind;
//    opens org.example.ibb_ecodation_javafx.ui.dragndrop to javafx.fxml, lombok, org.mapstruct, spring.beans;
//    opens org.example.ibb_ecodation_javafx.ui.splitpane to javafx.fxml, lombok, org.mapstruct, spring.beans;
//    opens org.example.ibb_ecodation_javafx.ui.chart to javafx.fxml, lombok, org.mapstruct, spring.beans;
//    opens org.example.ibb_ecodation_javafx.ui.table to javafx.fxml, javafx.base, lombok, org.mapstruct, spring.beans;
//    opens org.example.ibb_ecodation_javafx.ui.codehighlighter to javafx.fxml, javafx.base, lombok, org.mapstruct, spring.beans;
//    opens org.example.ibb_ecodation_javafx.mapper to spring.beans;
//    opens org.example.ibb_ecodation_javafx.repository  to javafx.fxml, javafx.base, lombok, org.mapstruct, spring.beans, spring.core;
////    opens org.example.ibb_ecodation_javafx.core.logger to javafx.fxml, javafx.base, lombok, org.mapstruct, spring.beans;
//    opens org.example.ibb_ecodation_javafx.core.i18n to javafx.fxml, javafx.base, lombok, org.mapstruct, spring.beans;
//    opens org.example.ibb_ecodation_javafx.core.service to javafx.fxml, javafx.base, lombok, org.mapstruct, spring.beans;
//    opens org.example.ibb_ecodation_javafx.backup to javafx.fxml, lombok, org.mapstruct, spring.beans;
//    opens org.example.ibb_ecodation_javafx.core.backup to javafx.fxml, lombok, org.mapstruct, spring.beans;
//    opens org.example.ibb_ecodation_javafx.model to com.fasterxml.jackson.databind;
//    opens org.example.ibb_ecodation_javafx.model.dto to com.fasterxml.jackson.databind;
//    opens org.example.ibb_ecodation_javafx.model.request to com.fasterxml.jackson.databind;
//    opens org.example.ibb_ecodation_javafx.model.response to com.fasterxml.jackson.databind;
//    opens org.example.ibb_ecodation_javafx.model.enums to com.fasterxml.jackson.databind;
//    opens org.example.ibb_ecodation_javafx.utils to javafx.fxml, javafx.base, lombok, org.mapstruct, spring.beans;
//    opens org.example.ibb_ecodation_javafx.core.db to javafx.fxml, javafx.base, lombok, org.mapstruct, spring.beans;
//    opens org.example.ibb_ecodation_javafx.config to javafx.fxml, javafx.base, lombok, org.mapstruct, spring.beans, spring.core;
//    opens org.example.ibb_ecodation_javafx.core.config to javafx.fxml, javafx.base, lombok, org.mapstruct, spring.beans, spring.core;
//    opens org.example.ibb_ecodation_javafx.repository.impl to javafx.fxml, javafx.base, lombok, org.mapstruct, spring.beans, spring.core;
//    requires de.jensd.fx.glyphs.fontawesome;
//    requires java.net.http;
//    requires org.apache.logging.log4j.core;
//    requires layout;
//    requires io;
//    requires kernel;
//    requires org.apache.commons.io;
//    requires static lombok;
//    requires org.mapstruct;
//    requires com.fasterxml.jackson.dataformat.yaml;
//
//    requires java.desktop;
//    requires java.sql;
//    requires spring.core;
//    requires spring.jdbc;
//    requires java.annotation;
//
////    exports org.example.ibb_ecodation_javafx.service.impl;
//    exports org.example.ibb_ecodation_javafx.core.db;
//    exports org.example.ibb_ecodation_javafx  to javafx.fxml, javafx.base, lombok, org.mapstruct, spring.beans, spring.core, javafx.graphics;
//
//    exports org.example.ibb_ecodation_javafx.properties;
//    exports org.example.ibb_ecodation_javafx.mapper;
//    exports org.example.ibb_ecodation_javafx.model;
//    exports org.example.ibb_ecodation_javafx.core.service;
//    exports org.example.ibb_ecodation_javafx.core.service.impl;
//    exports org.example.ibb_ecodation_javafx.utils;
//    exports org.example.ibb_ecodation_javafx.core.i18n;
//    exports org.example.ibb_ecodation_javafx.model.enums;
//    exports org.example.ibb_ecodation_javafx.model.dto;
//    exports org.example.ibb_ecodation_javafx.model.event;
//    exports org.example.ibb_ecodation_javafx.repository;
//
//    opens org.example.ibb_ecodation_javafx.model.event to org.mapstruct, spring.beans;
//    exports org.example.ibb_ecodation_javafx.core.mapper;
//    exports org.example.ibb_ecodation_javafx.config;
//    opens org.example.ibb_ecodation_javafx.core.mapper to spring.beans;
////    opens org.example.ibb_ecodation_javafx.service.impl to javafx.fxml, lombok, org.mapstruct, spring.beans;
//
//}